const quizData = {
  basic_linux_1: [
    { question: "What command is used to list files?", options: ["ls", "dir", "list", "files"], answer: "ls" },
    { question: "What is the root directory symbol?", options: ["/", "~", ".", ".."], answer: "/" },
    { question: "Which command is used to change the current directory?", options: ["cd", "chdir", "pwd", "ls"], answer: "cd" },
    { question: "Which command shows the current working directory?", options: ["pwd", "cwd", "where", "path"], answer: "pwd" },
    { question: "Which command is used to create a new directory?", options: ["mkdir", "newdir", "makedir", "createdir"], answer: "mkdir" },
    { question: "What command is used to remove an empty directory?", options: ["rmdir", "rm -r", "deldir", "removedir"], answer: "rmdir" },
    { question: "Which command is used to copy files?", options: ["cp", "copy", "cfile", "duplicate"], answer: "cp" },
    { question: "Which command is used to move or rename files?", options: ["mv", "move", "ren", "shift"], answer: "mv" },
    { question: "What command is used to remove files?", options: ["rm", "del", "erase", "delete"], answer: "rm" },
    { question: "Which command displays the content of a file?", options: ["cat", "view", "show", "display"], answer: "cat" },
    { question: "Which command is used to search for text in a file?", options: ["grep", "find", "search", "look"], answer: "grep" },
    { question: "Which command shows the manual page of another command?", options: ["man", "help", "info", "guide"], answer: "man" },
    { question: "Which command shows currently logged-in users?", options: ["who", "users", "w", "whoami"], answer: "who" },
    { question: "Which command is used to display the date and time?", options: ["date", "time", "clock", "now"], answer: "date" },
    { question: "Which command is used to display disk usage?", options: ["df", "du", "diskfree", "space"], answer: "df" },
    { question: "Which command shows file size and space usage per directory?", options: ["du", "df", "ls -lh", "size"], answer: "du" },
    { question: "Which command is used to show hidden files?", options: ["ls -a", "ls -h", "ls -hidden", "ls -s"], answer: "ls -a" },
    { question: "What command is used to display the first lines of a file?", options: ["head", "top", "first", "start"], answer: "head" },
    { question: "What command is used to display the last lines of a file?", options: ["tail", "bottom", "last", "end"], answer: "tail" },
    { question: "Which command is used to count words, lines, and characters in a file?", options: ["wc", "count", "linecount", "stats"], answer: "wc" },
    { question: "Which command is used to display running processes?", options: ["ps", "proc", "tasks", "process"], answer: "ps" },
    { question: "Which command shows the system's uptime?", options: ["uptime", "time", "sysup", "runtime"], answer: "uptime" },
    { question: "Which command is used to clear the terminal screen?", options: ["clear", "cls", "reset", "wipe"], answer: "clear" },
    { question: "Which command is used to log out from the terminal?", options: ["exit", "logout", "quit", "bye"], answer: "exit" },
    { question: "What symbol is used for the home directory?", options: ["~", "/", ".", ".."], answer: "~" },
    { question: "Which command shows network configuration?", options: ["ifconfig", "netstat", "ipconfig", "netconfig"], answer: "ifconfig" },
    { question: "Which command is used to display active network connections?", options: ["netstat", "ifconfig", "ping", "connections"], answer: "netstat" },
    { question: "Which command is used to test network connectivity?", options: ["ping", "test", "nettest", "connect"], answer: "ping" },
    { question: "Which command is used to download files from the internet?", options: ["wget", "curl", "fetch", "download"], answer: "wget" },
    { question: "Which command is used to change file permissions?", options: ["chmod", "chperm", "permset", "setperm"], answer: "chmod" },
  ],
  basic_microcontrollers_1: [
    { question: "What is a microcontroller?", options: ["A small computer on a single chip", "A type of transformer", "A memory chip", "A power supply unit"], answer: "A small computer on a single chip" },
    { question: "Which of the following is NOT a microcontroller family?", options: ["8051", "PIC", "ARM Cortex", "Pentium"], answer: "Pentium" },
    { question: "Which company developed the 8051 microcontroller?", options: ["Intel", "Atmel", "Microchip", "Texas Instruments"], answer: "Intel" },
    { question: "Which type of memory stores the microcontroller program?", options: ["ROM/Flash", "RAM", "Cache", "EEPROM"], answer: "ROM/Flash" },
    { question: "Which memory is volatile in a microcontroller?", options: ["RAM", "ROM", "Flash", "EEPROM"], answer: "RAM" },
    { question: "Which bus carries the address to memory?", options: ["Address bus", "Data bus", "Control bus", "Serial bus"], answer: "Address bus" },
    { question: "Which bus carries the actual data?", options: ["Data bus", "Address bus", "Control bus", "System bus"], answer: "Data bus" },
    { question: "What does ALU stand for in a microcontroller?", options: ["Arithmetic Logic Unit", "Automatic Logic Unit", "Arithmetic Level Unit", "Analog Logic Unit"], answer: "Arithmetic Logic Unit" },
    { question: "Which component executes program instructions?", options: ["CPU", "RAM", "ROM", "Timer"], answer: "CPU" },
    { question: "What does GPIO stand for?", options: ["General Purpose Input Output", "General Pin Input Output", "Global Port Input Output", "General Process Input Output"], answer: "General Purpose Input Output" },
    { question: "Which of the following is a common microcontroller clock speed?", options: ["16 MHz", "3 GHz", "500 MHz", "100 GHz"], answer: "16 MHz" },
    { question: "Which pin type is used to supply power to the microcontroller?", options: ["Vcc/Vdd", "GND", "GPIO", "CLK"], answer: "Vcc/Vdd" },
    { question: "What does the GND pin represent?", options: ["Ground", "Gain node", "Gate negative drain", "General node"], answer: "Ground" },
    { question: "What is the typical voltage for logic HIGH in many microcontrollers?", options: ["5V", "12V", "3.3V", "24V"], answer: "5V" },
    { question: "Which interface is used for serial communication?", options: ["UART", "PWM", "ADC", "GPIO"], answer: "UART" },
    { question: "Which module converts analog signals to digital?", options: ["ADC", "DAC", "PWM", "UART"], answer: "ADC" },
    { question: "Which module converts digital signals to analog?", options: ["DAC", "ADC", "PWM", "GPIO"], answer: "DAC" },
    { question: "What does PWM stand for?", options: ["Pulse Width Modulation", "Power Width Module", "Pulse Wave Module", "Power Wave Modulation"], answer: "Pulse Width Modulation" },
    { question: "Which protocol is synchronous?", options: ["SPI", "UART", "I2C", "Both SPI and I2C"], answer: "Both SPI and I2C" },
    { question: "What is the function of a watchdog timer?", options: ["Reset the system if it hangs", "Measure time", "Generate PWM", "Control LEDs"], answer: "Reset the system if it hangs" },
    { question: "Which of these is NOT an input device for a microcontroller?", options: ["Switch", "Sensor", "LED", "Button"], answer: "LED" },
    { question: "What does ISP stand for in microcontroller programming?", options: ["In-System Programming", "Internal Serial Port", "Input Signal Processing", "In-System Porting"], answer: "In-System Programming" },
    { question: "Which microcontroller is widely used in Arduino Uno?", options: ["ATmega328P", "PIC16F877A", "STM32F103", "8051"], answer: "ATmega328P" },
    { question: "Which microcontroller architecture uses Harvard design?", options: ["PIC", "8051", "AVR", "All of the above"], answer: "All of the above" },
    { question: "Which timer mode counts external pulses?", options: ["Counter mode", "Timer mode", "PWM mode", "Capture mode"], answer: "Counter mode" },
    { question: "What does I2C stand for?", options: ["Inter-Integrated Circuit", "Internal Integrated Communication", "Inter-Interface Connection", "Integrated Internal Circuit"], answer: "Inter-Integrated Circuit" },
    { question: "Which microcontroller feature allows multitasking?", options: ["Interrupts", "GPIO", "Timers", "PWM"], answer: "Interrupts" },
    { question: "Which flag indicates arithmetic overflow?", options: ["Overflow flag", "Carry flag", "Zero flag", "Sign flag"], answer: "Overflow flag" },
    { question: "Which register holds the address of the next instruction?", options: ["Program Counter", "Stack Pointer", "Instruction Register", "Base Register"], answer: "Program Counter" },
    { question: "Which memory stores variables during execution?", options: ["RAM", "ROM", "Flash", "EEPROM"], answer: "RAM" },
],
  basic_C_Programming_1: [
    { question: "Which function is used to get input from the user in C?", options: ["scanf()", "printf()", "gets()", "puts()"], answer: "scanf()" },
    { question: "What is the default return type of the main() function in C?", options: ["int", "void", "float", "char"], answer: "int" },
    { question: "Which symbol is used to indicate a preprocessor directive?", options: ["#", "$", "@", "&"], answer: "#" },
    { question: "What is the correct syntax to declare an integer variable?", options: ["int x;", "integer x;", "num x;", "var x;"], answer: "int x;" },
    { question: "Which of the following is a valid comment in C?", options: ["// comment", "/* comment */", "# comment", "Both // comment and /* comment */"], answer: "Both // comment and /* comment */" },
    { question: "Which operator is used to access the address of a variable?", options: ["&", "*", "@", "%"], answer: "&" },
    { question: "Which operator is used for pointer dereferencing?", options: ["*", "&", "#", "@"], answer: "*" },
    { question: "Which function is used to find the length of a string?", options: ["strlen()", "strlength()", "len()", "length()"], answer: "strlen()" },
    { question: "What is the correct syntax for a for loop in C?", options: ["for(init; condition; increment)", "for(condition; increment; init)", "for(init, increment, condition)", "for(condition, init, increment)"], answer: "for(init; condition; increment)" },
    { question: "Which escape sequence is used for a new line?", options: ["\\n", "\\t", "\\r", "\\b"], answer: "\\n" },
    { question: "Which function is used to open a file in C?", options: ["fopen()", "open()", "file_open()", "openfile()"], answer: "fopen()" },
    { question: "What is the correct way to close a file in C?", options: ["fclose()", "close()", "endfile()", "stopfile()"], answer: "fclose()" },
    { question: "Which keyword is used to define a constant in C?", options: ["const", "constant", "define", "Both const and #define"], answer: "Both const and #define" },
    { question: "What is the size of int on most 32-bit systems?", options: ["4 bytes", "2 bytes", "8 bytes", "Depends on compiler"], answer: "4 bytes" },
    { question: "Which format specifier is used for printing integers?", options: ["%d", "%f", "%c", "%s"], answer: "%d" },
    { question: "Which format specifier is used for printing floating-point numbers?", options: ["%f", "%d", "%lf", "%s"], answer: "%f" },
    { question: "Which format specifier is used for printing characters?", options: ["%c", "%d", "%s", "%f"], answer: "%c" },
    { question: "Which format specifier is used for printing strings?", options: ["%s", "%d", "%c", "%f"], answer: "%s" },
    { question: "Which function is used to compare two strings?", options: ["strcmp()", "strcompare()", "compare()", "stringcmp()"], answer: "strcmp()" },
    { question: "Which loop executes at least once regardless of condition?", options: ["do...while", "while", "for", "None"], answer: "do...while" },
    { question: "What is the value of an uninitialized local variable?", options: ["Garbage value", "0", "NULL", "Undefined"], answer: "Garbage value" },
    { question: "Which keyword is used to exit from a loop?", options: ["break", "exit", "stop", "return"], answer: "break" },
    { question: "Which keyword is used to skip the current iteration of a loop?", options: ["continue", "skip", "pass", "goto"], answer: "continue" },
    { question: "Which statement is used to stop the execution of a program?", options: ["exit()", "break", "stop", "terminate"], answer: "exit()" },
    { question: "What is the correct syntax for an if statement?", options: ["if(condition)", "if condition then", "if(condition) then", "if: condition"], answer: "if(condition)" },
    { question: "Which keyword is used to define a structure in C?", options: ["struct", "structure", "define_struct", "type_struct"], answer: "struct" },
    { question: "Which keyword is used to define a union in C?", options: ["union", "struct", "combine", "merge"], answer: "union" },
    { question: "Which operator is used for logical AND?", options: ["&&", "&", "and", "AND"], answer: "&&" },
    { question: "Which operator is used for logical OR?", options: ["||", "|", "or", "OR"], answer: "||" },
    { question: "Which operator is used for logical NOT?", options: ["!", "~", "not", "NOT"], answer: "!" },
],
  basic_linux_2: [
    { question: "Which command is used to change file ownership?", options: ["chown", "owner", "setown", "setuser"], answer: "chown" },
    { question: "Which command is used to compress files?", options: ["gzip", "zip", "compress", "pack"], answer: "gzip" },
    { question: "Which command is used to uncompress `.gz` files?", options: ["gunzip", "unzip", "extract", "unpack"], answer: "gunzip" },
    { question: "Which command is used to search for files?", options: ["find", "search", "locate", "whereis"], answer: "find" },
    { question: "Which command is used to quickly locate files using a database?", options: ["locate", "find", "search", "track"], answer: "locate" },
    { question: "Which command is used to display kernel version?", options: ["uname -r", "version", "kernver", "sysver"], answer: "uname -r" },
    { question: "Which command is used to display all system information?", options: ["uname -a", "sysinfo", "info", "system"], answer: "uname -a" },
    { question: "Which command is used to display memory usage?", options: ["free", "meminfo", "mem", "ram"], answer: "free" },
    { question: "Which command is used to monitor system processes in real time?", options: ["top", "htop", "monitor", "procview"], answer: "top" },
    { question: "Which command is used to list block devices?", options: ["lsblk", "blklist", "diskls", "blockdev"], answer: "lsblk" },
    { question: "Which command is used to safely shut down the system?", options: ["shutdown", "poweroff", "halt", "off"], answer: "shutdown" },
    { question: "Which command is used to restart the system?", options: ["reboot", "restart", "shutdown -r", "boot"], answer: "reboot" },
    { question: "Which command is used to print text to the terminal?", options: ["echo", "print", "say", "output"], answer: "echo" },
    { question: "Which command shows the command history?", options: ["history", "cmdlog", "cmdhist", "log"], answer: "history" },
    { question: "Which command is used to display a calendar?", options: ["cal", "calendar", "date", "month"], answer: "cal" },
    { question: "Which command is used to display help for shell built-ins?", options: ["help", "man", "info", "assist"], answer: "help" },
    { question: "Which command is used to switch users?", options: ["su", "switch", "user", "login"], answer: "su" },
    { question: "Which command is used to show all environment variables?", options: ["env", "set", "export", "vars"], answer: "env" },
    { question: "Which command is used to set environment variables?", options: ["export", "setenv", "envset", "assign"], answer: "export" },
    { question: "Which command is used to display system boot messages?", options: ["dmesg", "bootlog", "syslog", "messages"], answer: "dmesg" },
    { question: "Which command is used to list files in a directory?", options: ["ls", "dir", "list", "show"], answer: "ls" },
    { question: "Which command is used to display the current working directory?", options: ["pwd", "cwd", "workdir", "dirpwd"], answer: "pwd" },
    { question: "Which command is used to move or rename a file?", options: ["mv", "cp", "rename", "move"], answer: "mv" },
    { question: "Which command is used to display the contents of a file?", options: ["cat", "show", "see", "open"], answer: "cat" },
    { question: "Which command is used to create a new empty file?", options: ["touch", "newfile", "create", "file"], answer: "touch" },
    { question: "Which command is used to create a new directory?", options: ["mkdir", "makedir", "dircreate", "newdir"], answer: "mkdir" },
    { question: "Which command is used to delete a directory?", options: ["rmdir", "removedir", "deldir", "rm -d"], answer: "rmdir" },
    { question: "Which command is used to search text in a file?", options: ["grep", "find", "search", "look"], answer: "grep" },
    { question: "Which command is used to show currently logged-in users?", options: ["who", "users", "w", "login"], answer: "who" },
    { question: "Which command is used to display the system date and time?", options: ["date", "time", "clock", "showtime"], answer: "date" }
  ],
  basic_microcontrollers_2: [
    { question: "What does EEPROM stand for?", options: ["Electrically Erasable Programmable Read-Only Memory", "Electronically Editable Permanent Read-Only Memory", "Extended Erasable Program Memory", "Electrical Editable Processing Memory"], answer: "Electrically Erasable Programmable Read-Only Memory" },
    { question: "Which unit handles arithmetic and logic operations?", options: ["ALU", "CPU", "Control Unit", "FPU"], answer: "ALU" },
    { question: "Which microcontroller pin type is used for external clock input?", options: ["XTAL", "Vcc", "GND", "GPIO"], answer: "XTAL" },
    { question: "Which of these is an example of an ARM Cortex-M series microcontroller?", options: ["STM32F103", "ATmega328P", "PIC16F877A", "8051"], answer: "STM32F103" },
    { question: "What is the main difference between microcontroller and microprocessor?", options: ["Microcontroller has built-in memory and peripherals", "Microcontroller is faster", "Microcontroller is larger", "Microcontroller has no CPU"], answer: "Microcontroller has built-in memory and peripherals" },
    { question: "What is the smallest addressable unit of memory?", options: ["Byte", "Bit", "Word", "Nibble"], answer: "Byte" },
    { question: "Which of these is used to generate delays?", options: ["Timers", "Counters", "Interrupts", "ADC"], answer: "Timers" },
    { question: "Which component stores return addresses during function calls?", options: ["Stack", "Heap", "Register", "Flash"], answer: "Stack" },
    { question: "Which microcontroller feature is used for motor speed control?", options: ["PWM", "ADC", "UART", "I2C"], answer: "PWM" },
    { question: "Which of these is an example of 8-bit microcontroller?", options: ["ATmega328P", "STM32F103", "ESP32", "ARM Cortex-M4"], answer: "ATmega328P" },
    { question: "What does ISP allow you to do?", options: ["Program the MCU without removing it from the circuit", "Increase clock speed", "Change voltage levels", "Store data permanently"], answer: "Program the MCU without removing it from the circuit" },
    { question: "Which of these is a wireless communication protocol?", options: ["Bluetooth", "UART", "SPI", "I2C"], answer: "Bluetooth" },
    { question: "What does the reset pin do?", options: ["Restart the microcontroller", "Turn off power", "Clear memory", "Erase flash"], answer: "Restart the microcontroller" },
    { question: "Which clock source is internal to microcontrollers?", options: ["RC oscillator", "Crystal oscillator", "External clock", "Phase-locked loop"], answer: "RC oscillator" },
    { question: "Which clock source is more accurate?", options: ["Crystal oscillator", "RC oscillator", "Internal clock", "Random clock"], answer: "Crystal oscillator" },
    { question: "Which communication protocol uses two wires SDA and SCL?", options: ["I2C", "SPI", "UART", "CAN"], answer: "I2C" },
    { question: "Which communication protocol uses MOSI, MISO, SCK, and CS pins?", options: ["SPI", "I2C", "UART", "PWM"], answer: "SPI" },
    { question: "Which of these microcontrollers is Wi-Fi enabled?", options: ["ESP8266", "ATmega328P", "PIC16F877A", "STM32F103"], answer: "ESP8266" },
    { question: "What is the function of the bootloader?", options: ["Load programs into flash memory", "Reset the microcontroller", "Generate clock", "Manage GPIO"], answer: "Load programs into flash memory" },
    { question: "Which instruction is used to stop program execution until an interrupt occurs?", options: ["Sleep", "NOP", "HALT", "WAIT"], answer: "Sleep" },
    { question: "Which register is used to store the program counter value in a microcontroller?", options: ["PC", "IR", "ACC", "SP"], answer: "PC" },
    { question: "What is the function of the Watchdog Timer in microcontrollers?", options: ["Reset system on failure", "Increase clock speed", "Store data permanently", "Generate PWM signals"], answer: "Reset system on failure" },
    { question: "Which type of memory is volatile in microcontrollers?", options: ["RAM", "ROM", "EEPROM", "Flash"], answer: "RAM" },
    { question: "Which bus is responsible for transferring data between CPU and peripherals?", options: ["Data Bus", "Address Bus", "Control Bus", "Power Bus"], answer: "Data Bus" },
    { question: "Which pin provides the main power supply to a microcontroller?", options: ["Vcc", "GND", "RESET", "XTAL"], answer: "Vcc" },
    { question: "Which microcontroller component is responsible for instruction execution?", options: ["CPU", "I/O Ports", "Oscillator", "Timers"], answer: "CPU" },
    { question: "Which register stores the return address during a function call?", options: ["Stack Pointer", "Program Counter", "Accumulator", "Instruction Register"], answer: "Stack Pointer" },
    { question: "Which communication protocol is synchronous?", options: ["SPI", "UART", "I2C", "RS232"], answer: "SPI" },
    { question: "Which microcontroller feature is used to generate precise time delays?", options: ["Timers", "ADC", "Interrupts", "PWM"], answer: "Timers" },
    { question: "Which microcontroller pin is used to reset the system?", options: ["RESET", "Vcc", "CLK", "TX"], answer: "RESET" }
  ],
  basic_C_Programming_2: [
    { question: "Which function is used to dynamically allocate memory?", options: ["malloc()", "alloc()", "new()", "allocate()"], answer: "malloc()" },
    { question: "Which function is used to release dynamically allocated memory?", options: ["free()", "delete()", "remove()", "release()"], answer: "free()" },
    { question: "Which function is used to set a block of memory to a specific value?", options: ["memset()", "memfill()", "fillmem()", "setmem()"], answer: "memset()" },
    { question: "Which keyword is used to return a value from a function?", options: ["return", "give", "send", "yield"], answer: "return" },
    { question: "Which function is the entry point of every C program?", options: ["main()", "start()", "begin()", "init()"], answer: "main()" },
    { question: "Which operator is used for modulo division?", options: ["%", "/", "mod", "rem"], answer: "%" },
    { question: "Which operator is used to increment a variable by 1?", options: ["++", "+", "+=", "inc"], answer: "++" },
    { question: "Which operator is used to decrement a variable by 1?", options: ["--", "-", "-=", "dec"], answer: "--" },
    { question: "Which function is used to generate a random number?", options: ["rand()", "random()", "genrand()", "randomize()"], answer: "rand()" },
    { question: "Which operator is used to assign a value to a variable?", options: ["=", "==", ":=", "<-"], answer: "=" },
    { question: "What is the purpose of sizeof() operator?", options: ["To get size in bytes", "To count variables", "To check type", "To calculate memory speed"], answer: "To get size in bytes" },
    { question: "Which escape sequence represents a tab space?", options: ["\\t", "\\n", "\\r", "\\b"], answer: "\\t" },
    { question: "Which escape sequence represents a backslash?", options: ["\\\\", "\\b", "\\s", "\\n"], answer: "\\\\" },
    { question: "Which keyword is used for defining an enumeration?", options: ["enum", "enumerate", "define_enum", "list"], answer: "enum" },
    { question: "Which keyword is used for creating type aliases?", options: ["typedef", "alias", "typealias", "newtype"], answer: "typedef" },
    { question: "What is the output of printf(\"%d\", 5 > 2); ?", options: ["1", "0", "True", "False"], answer: "1" },
    { question: "What is the output of printf(\"%d\", 5 == 2); ?", options: ["0", "1", "True", "False"], answer: "0" },
    { question: "What will be the value of x after x = 5; x += 3; ?", options: ["8", "5", "3", "15"], answer: "8" },
    { question: "Which operator is used to access the value at the address stored in a pointer?", options: ["*", "&", "->", "%"], answer: "*" },
    { question: "Which keyword is used to define a constant in C?", options: ["const", "static", "final", "define"], answer: "const" },
    { question: "Which function is used to compare two strings in C?", options: ["strcmp()", "strcpy()", "strlen()", "strcat()"], answer: "strcmp()" },
    { question: "Which function is used to copy one string into another?", options: ["strcpy()", "strcat()", "strlen()", "strcmp()"], answer: "strcpy()" },
    { question: "Which function is used to find the length of a string?", options: ["strlen()", "strcpy()", "strcat()", "strcmp()"], answer: "strlen()" },
    { question: "Which keyword is used to exit from a loop immediately?", options: ["break", "exit", "continue", "stop"], answer: "break" },
    { question: "Which keyword is used to skip the current iteration in a loop?", options: ["continue", "break", "skip", "return"], answer: "continue" },
    { question: "Which function is used to open a file in C?", options: ["fopen()", "open()", "fileopen()", "opfile()"], answer: "fopen()" },
    { question: "Which function is used to close a file in C?", options: ["fclose()", "close()", "endfile()", "exit()"], answer: "fclose()" },
    { question: "Which symbol is used to represent a single-line comment in C?", options: ["//", "/*", "#", "--"], answer: "//" }
  ],
  linux: [
    { question: "What command is used to list files?", options: ["ls", "dir", "list"], answer: "ls" },
    { question: "What is the root directory symbol?", options: ["/", "~", "."], answer: "/" }
  ],
  microcontrollers: [
    { question: "Which is a popular microcontroller?", options: ["Arduino UNO", "Raspberry Pi", "ESP8266"], answer: "Arduino UNO" }
  ],
  cprogramming: [
    { question: "Which header file is used for printf?", options: ["<stdio.h>", "<stdlib.h>", "<string.h>"], answer: "<stdio.h>" },
    {  
      question: "What will be the output of the following code?<br><pre>#include &lt;stdio.h&gt;<br>int main() {<br>    printf(\"%d\", 5 + 3);<br>    return 0;<br>}</pre>",
      options: ["5", "8", "Error"],
      answer: "8" 
    }
  ]
};
